version: "3.8"

services:
  app:
    container_name: lerchat
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src
    networks:
      - dft

networks:
  dft:
    name: lerchat-net
